# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    CORENAME: mame2010

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'
    
  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'
    
  # MacOS 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-x64.yml'

  ################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-jni.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

##############################################################################
#################################### STAGES ##################################
##############################################################################
#
################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .core-defs
    - .libretro-windows-x64-mingw-make-default
  variables:
    CC:       x86_64-w64-mingw32-g++
    CXX:      x86_64-w64-mingw32-g++
    CC_AS:    x86_64-w64-mingw32-gcc
    AR:       x86_64-w64-mingw32-ar
    NATIVELD: x86_64-w64-mingw32-ld
    LD:       x86_64-w64-mingw32-ld
    
# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .core-defs
    - .libretro-linux-x64-make-default

# MacOS 64-bit
libretro-build-osx-x64:
  extends:
    - .libretro-osx-x64-make-default
    - .core-defs

################################### CELLULAR #################################
# Android ARMv7a
android-armeabi-v7a:
  extends:
    - .core-defs
    - .libretro-android-jni-armeabi-v7a

# Android ARMv8a
android-arm64-v8a:
  extends:
    - .core-defs
    - .libretro-android-jni-arm64-v8a

# Android 64-bit x86
android-x86_64:
  extends:
    - .core-defs
    - .libretro-android-jni-x86_64
